version: 'v2.29.2-desktop.2'
services:
  db:
    container_name: postgres
    image: postgres
    restart: always
    build: ./db/
    environment:
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: mydb
      POSTGRES_USER: myuser
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql 
    ports:
      - 5432:5432
    networks:
      - net
  admin:
    restart: always
    build: ./admin/
    ports:
      - 8000:8000
    depends_on:
      - db
    networks:
      - net
    command: [ "./wait-for-it/wait-for-it.sh", "db:5432","-t" ,"20", "--", "go", "run", "./cmd/main.go" ]

  promocodes:
    restart: always
    build: ./promocodes/
    ports:
      - 8001:8001
    depends_on:
      - db
    networks:
      - net
    command: [ "./wait-for-it/wait-for-it.sh", "db:5432","-t" ,"20", "--", "go", "run", "./cmd/main.go"]

networks:
  net:
    driver: bridge
